import { Category, Transaction, UserSettings } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  // Expense Categories
  { id: 'cat-food', name: 'Food & Dining', type: 'expense', icon: 'Utensils', color: '#FF9500', bgColor: '#FFF4E5' },
  { id: 'cat-groceries', name: 'Groceries', type: 'expense', icon: 'ShoppingCart', color: '#34C759', bgColor: '#EBF9EE' },
  { id: 'cat-housing', name: 'Housing & Rent', type: 'expense', icon: 'Home', color: '#007AFF', bgColor: '#E5F1FF' },
  { id: 'cat-utilities', name: 'Utilities & Bills', type: 'expense', icon: 'Zap', color: '#5856D6', bgColor: '#EFEFFB' },
  { id: 'cat-transport', name: 'Transport & Fuel', type: 'expense', icon: 'Car', color: '#FF2D55', bgColor: '#FFEAEF' },
  { id: 'cat-shopping', name: 'Shopping & Gear', type: 'expense', icon: 'ShoppingBag', color: '#AF52DE', bgColor: '#F6EEFB' },
  { id: 'cat-entertainment', name: 'Entertainment', type: 'expense', icon: 'Film', color: '#FF3B30', bgColor: '#FFECEB' },
  { id: 'cat-health', name: 'Health & Fitness', type: 'expense', icon: 'HeartPulse', color: '#30B0C7', bgColor: '#E8F7F9' },
  { id: 'cat-subscriptions', name: 'Subscriptions', type: 'expense', icon: 'CreditCard', color: '#64D2FF', bgColor: '#EBF9FF' },
  { id: 'cat-travel', name: 'Travel & Vacations', type: 'expense', icon: 'Plane', color: '#FFCC00', bgColor: '#FFFBE5' },
  { id: 'cat-other-exp', name: 'Miscellaneous', type: 'expense', icon: 'MoreHorizontal', color: '#8E8E93', bgColor: '#F2F2F7' },

  // Income Categories
  { id: 'cat-salary', name: 'Main Salary', type: 'income', icon: 'Briefcase', color: '#34C759', bgColor: '#EBF9EE' },
  { id: 'cat-freelance', name: 'Freelance & Side Gig', type: 'income', icon: 'Laptop', color: '#007AFF', bgColor: '#E5F1FF' },
  { id: 'cat-investment', name: 'Investments & Dividends', type: 'income', icon: 'TrendingUp', color: '#5856D6', bgColor: '#EFEFFB' },
  { id: 'cat-gift', name: 'Gifts & Bonus', type: 'income', icon: 'Gift', color: '#FF9500', bgColor: '#FFF4E5' },
  { id: 'cat-other-inc', name: 'Other Income', type: 'income', icon: 'Coins', color: '#30B0C7', bgColor: '#E8F7F9' },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
  userName: 'Alex Chen',
  currency: 'USD',
  currencySymbol: '$',
  monthlyBudget: 3400,
  savingsGoal: 1000,
  resetDayOfMonth: 1,
  theme: 'light',
  enableHaptics: true,
  notifyThreshold: 80,
  avatarEmoji: '🍏',
};

// Seed realistic transactions for current month (August 2026) and previous 2 months (July 2026, June 2026)
export function getInitialSeedTransactions(): Transaction[] {
  return [
    // August 2026 (Current Month)
    {
      id: 'tx-001',
      title: 'TechCorp Salary',
      amount: 4800.0,
      type: 'income',
      categoryId: 'cat-salary',
      date: '2026-08-01',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      notes: 'Monthly direct deposit paycheck',
      tags: ['Primary Income'],
      createdAt: Date.now() - 23 * 86400000,
    },
    {
      id: 'tx-002',
      title: 'Apartment Monthly Rent',
      amount: 1450.0,
      type: 'expense',
      categoryId: 'cat-housing',
      date: '2026-08-02',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      notes: 'August rent + parking spot',
      tags: ['Fixed Bills'],
      createdAt: Date.now() - 22 * 86400000,
    },
    {
      id: 'tx-003',
      title: 'Whole Foods Market',
      amount: 142.85,
      type: 'expense',
      categoryId: 'cat-groceries',
      date: '2026-08-04',
      paymentMethod: 'Apple Pay',
      notes: 'Weekly organic groceries and fruits',
      tags: ['Food'],
      createdAt: Date.now() - 20 * 86400000,
    },
    {
      id: 'tx-004',
      title: 'Electric & Wi-Fi Utility',
      amount: 115.4,
      type: 'expense',
      categoryId: 'cat-utilities',
      date: '2026-08-06',
      paymentMethod: 'Credit Card',
      recurring: 'monthly',
      notes: 'Power grid + 1Gbps Fiber internet',
      tags: ['Utilities'],
      createdAt: Date.now() - 18 * 86400000,
    },
    {
      id: 'tx-005',
      title: 'Freelance UI/UX Project',
      amount: 750.0,
      type: 'income',
      categoryId: 'cat-freelance',
      date: '2026-08-08',
      paymentMethod: 'Bank Transfer',
      notes: 'Mobile app design milestone payout',
      tags: ['Side Project'],
      createdAt: Date.now() - 16 * 86400000,
    },
    {
      id: 'tx-006',
      title: 'Sushi Omakase Dinner',
      amount: 88.5,
      type: 'expense',
      categoryId: 'cat-food',
      date: '2026-08-10',
      paymentMethod: 'Apple Pay',
      notes: 'Dinner with college friends',
      tags: ['Dining'],
      createdAt: Date.now() - 14 * 86400000,
    },
    {
      id: 'tx-007',
      title: 'Apple One Subscription',
      amount: 37.95,
      type: 'expense',
      categoryId: 'cat-subscriptions',
      date: '2026-08-11',
      paymentMethod: 'Apple Pay',
      recurring: 'monthly',
      notes: 'iCloud 2TB + Music + Fitness+',
      tags: ['Digital'],
      createdAt: Date.now() - 13 * 86400000,
    },
    {
      id: 'tx-008',
      title: 'Trader Joe’s Stock Up',
      amount: 94.2,
      type: 'expense',
      categoryId: 'cat-groceries',
      date: '2026-08-14',
      paymentMethod: 'Debit Card',
      notes: 'Snacks, bakery & pantry staples',
      tags: ['Food'],
      createdAt: Date.now() - 10 * 86400000,
    },
    {
      id: 'tx-009',
      title: 'Uber Rides to Downtown',
      amount: 45.6,
      type: 'expense',
      categoryId: 'cat-transport',
      date: '2026-08-16',
      paymentMethod: 'Apple Pay',
      notes: 'Weekend transit',
      tags: ['Commute'],
      createdAt: Date.now() - 8 * 86400000,
    },
    {
      id: 'tx-010',
      title: 'Gym & Crossfit Pass',
      amount: 85.0,
      type: 'expense',
      categoryId: 'cat-health',
      date: '2026-08-18',
      paymentMethod: 'Credit Card',
      recurring: 'monthly',
      notes: 'Monthly club membership',
      tags: ['Health'],
      createdAt: Date.now() - 6 * 86400000,
    },
    {
      id: 'tx-011',
      title: 'IMAX Cinema Tickets',
      amount: 38.0,
      type: 'expense',
      categoryId: 'cat-entertainment',
      date: '2026-08-20',
      paymentMethod: 'Apple Pay',
      notes: 'Sci-fi movie premiere',
      tags: ['Leisure'],
      createdAt: Date.now() - 4 * 86400000,
    },
    {
      id: 'tx-012',
      title: 'Artisan Coffee & Croissant',
      amount: 14.75,
      type: 'expense',
      categoryId: 'cat-food',
      date: '2026-08-23',
      paymentMethod: 'Apple Pay',
      notes: 'Morning workspace coffee',
      tags: ['Cafe'],
      createdAt: Date.now() - 1 * 86400000,
    },

    // July 2026
    {
      id: 'tx-013',
      title: 'TechCorp Salary',
      amount: 4800.0,
      type: 'income',
      categoryId: 'cat-salary',
      date: '2026-07-01',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      notes: 'Monthly salary',
      createdAt: Date.now() - 54 * 86400000,
    },
    {
      id: 'tx-014',
      title: 'Apartment Monthly Rent',
      amount: 1450.0,
      type: 'expense',
      categoryId: 'cat-housing',
      date: '2026-07-02',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      createdAt: Date.now() - 53 * 86400000,
    },
    {
      id: 'tx-015',
      title: 'Groceries & Farmers Market',
      amount: 410.0,
      type: 'expense',
      categoryId: 'cat-groceries',
      date: '2026-07-12',
      paymentMethod: 'Credit Card',
      createdAt: Date.now() - 43 * 86400000,
    },
    {
      id: 'tx-016',
      title: 'Summer Flight to Lake Tahoe',
      amount: 340.0,
      type: 'expense',
      categoryId: 'cat-travel',
      date: '2026-07-18',
      paymentMethod: 'Credit Card',
      notes: 'Roundtrip cabin vacation',
      createdAt: Date.now() - 37 * 86400000,
    },
    {
      id: 'tx-017',
      title: 'Dining Out & Brunch',
      amount: 220.0,
      type: 'expense',
      categoryId: 'cat-food',
      date: '2026-07-24',
      paymentMethod: 'Apple Pay',
      createdAt: Date.now() - 31 * 86400000,
    },
    {
      id: 'tx-018',
      title: 'Utilities & Bills',
      amount: 128.0,
      type: 'expense',
      categoryId: 'cat-utilities',
      date: '2026-07-05',
      paymentMethod: 'Credit Card',
      createdAt: Date.now() - 50 * 86400000,
    },

    // June 2026
    {
      id: 'tx-019',
      title: 'TechCorp Salary',
      amount: 4800.0,
      type: 'income',
      categoryId: 'cat-salary',
      date: '2026-06-01',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      createdAt: Date.now() - 84 * 86400000,
    },
    {
      id: 'tx-020',
      title: 'Apartment Monthly Rent',
      amount: 1450.0,
      type: 'expense',
      categoryId: 'cat-housing',
      date: '2026-06-02',
      paymentMethod: 'Bank Transfer',
      recurring: 'monthly',
      createdAt: Date.now() - 83 * 86400000,
    },
    {
      id: 'tx-021',
      title: 'Stock Dividend Payout',
      amount: 320.0,
      type: 'income',
      categoryId: 'cat-investment',
      date: '2026-06-15',
      paymentMethod: 'Bank Transfer',
      createdAt: Date.now() - 70 * 86400000,
    },
    {
      id: 'tx-022',
      title: 'Groceries (Monthly)',
      amount: 385.0,
      type: 'expense',
      categoryId: 'cat-groceries',
      date: '2026-06-16',
      paymentMethod: 'Debit Card',
      createdAt: Date.now() - 69 * 86400000,
    },
    {
      id: 'tx-023',
      title: 'Wireless Earbuds',
      amount: 179.0,
      type: 'expense',
      categoryId: 'cat-shopping',
      date: '2026-06-20',
      paymentMethod: 'Apple Pay',
      createdAt: Date.now() - 65 * 86400000,
    },
    {
      id: 'tx-024',
      title: 'Utilities & Subscriptions',
      amount: 165.0,
      type: 'expense',
      categoryId: 'cat-utilities',
      date: '2026-06-08',
      paymentMethod: 'Credit Card',
      createdAt: Date.now() - 77 * 86400000,
    },
  ];
}
